config/routes.rb
Rails.application.routes.draw do
  resources :meals
  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :edit, :update]

  get 'limit/:id', to: 'users#limit_edit', as: 'edit_limit'
  post 'limit/:id', to: 'users#limit_update'
  get 'history', to: 'meals#meals_history', as: 'meals_history'

  get 'filter', to: 'meals#filter_new', as: 'filter'
  post 'filter', to: 'meals#filter', as: 'filter_show'

  get 'manager', to: 'users#manager_panel'
  get 'admin', to: 'users#admin_panel'
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  post 'users/:id/toggle_manager', to: 'users#toggle_manager', as: 'toggle_manager'

  get 'admin/new_user', to: 'users#admin_new_user'
  post 'admin/new_user', to: 'users#admin_add_user'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
  validates_presence_of :date, :meal_type, :name, :calories
  validates :calories, numericality: { greater_than_or_equal_to: 0 }
  scope :having_date_between, ->(start_date, end_date) {
    where("date BETWEEN '#{start_date.values.first}' AND '#{end_date.values.first}'").order('date DESC')
  }

  def self.todays_meals
    where(date: Date.today)
  end

  def self.meal_types
    %w(Breakfast Lunch Dinner)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :meals, dependent: :delete_all
  enum role: { user: 0, manager: 1, admin: 2 }

  def calories_taken
    sum = 0
    Meal.todays_meals.each { |m| sum += m.calories if m.user_id == self.id }
    sum
  end

  def calories_left
    self.daily_calories - calories_taken
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:daily_calories])
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @user_meals = current_user.meals.todays_meals.paginate(page: params[:page], per_page: 5)
  end

  def new
    @meal = current_user.meals.new
  end

  def create
    @meal = current_user.meals.new(meal_params)
    if @meal.save
      flash[:success] = 'Meal was successfully added'
      redirect_to meals_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @meal.update(meal_params)
      flash[:success] = 'Meal was successfully updated'
      case
      when current_user.manager?
        redirect_to manager_path
      when current_user.admin?
        redirect_to admin_path
      else
        redirect_to meals_path
      end
    else
      render 'edit'
    end
  end

  def show

  end

  def destroy
    @meal.destroy
    flash[:success] = 'Meal was successfully removed'
    case
    when current_user.manager?
      redirect_to manager_path
    when current_user.admin?
      redirect_to admin_path
    else
      redirect_to meals_path
    end
  end

  def meals_history
    @user_meals = current_user.meals.paginate(page: params[:page], per_page: 5)
    @meals_all = Meal.all.order(:date).paginate(page: params[:page], per_page: 5)
  end

  def filter_new
    @filtered_meals = current_user.meals.order(:date).paginate(page: params[:page], per_page: 5)
  end

  def filter
    @filtered_meals = current_user.meals.
        having_date_between(params.require(:filter).permit(:start_date),
                            params.require(:filter).permit(:end_date))
                          .order(:date)
                          .paginate(page: params[:page], per_page: 5)
    render 'filter'
  end

  private

  def set_meal
    @meal = Meal.find(params[:id])
  end

  def meal_params
    params.require(:meal).permit(:date, :meal_type, :name, :calories, :user_id)
  end

  def require_same_user
    if current_user != @meal.user and !current_user.admin? and !current_user.manager?
      flash[:notice] = "You can only edit your meals"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_manager, only: [:manager_panel]
  before_action :require_admin, only: [:admin_panel, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :limit_edit, :limit_update, :toggle_manager]
  before_action :require_staff, only: [:show]

  def manager_panel
    @meals_all = Meal.order(:date).paginate(page: params[:page], per_page: 5)
  end

  def admin_panel
    @meals_all = Meal.order(:date).paginate(page: params[:page], per_page: 5)
  end

  def show
    @user_meals = @user.meals.order(:date).paginate(page: params[:page], per_page: 5)
  end

  def edit

  end

  def update
    if @user.update(user_params)
      flash[:success] = 'User was successfully updated'
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash.notice = "User '#{@user.email}' was deleted"
    redirect_to admin_path
  end

  def toggle_manager
    if @user.manager?
      @user.user!
    elsif @user.user?
      @user.manager!
    end
    redirect_to admin_path
  end

  def admin_new_user
    @user = User.new
  end

  def admin_add_user
    if User.create(user_params)
      flash[:notice] = 'User was successfully added'
      redirect_to admin_path
    else
      render 'admin_new_user'
    end
  end

  def limit_edit

  end

  def limit_update
    if @user.update(limit_params)
      flash[:success] = 'Daily limit was successfully updated'
      case
      when current_user.manager?
        redirect_to manager_path
      when current_user.admin?
        redirect_to admin_path
      else
        redirect_to meals_path
      end
    else
      render 'limit_edit'
    end
  end

  private

  def require_manager
    if !current_user.manager?
      redirect_to root_path
      flash[:notice] = 'You are not a manager'
    end
  end

  def require_admin
    if !current_user.admin?
      redirect_to root_path
      flash[:notice] = 'You are not an admin'
    end
  end

  def require_staff
    if !current_user.admin? and !current_user.manager?
      redirect_to root_path
      flash[:notice] = 'You are cannot do that action'
    end
  end

  def limit_params
    params.require(:user).permit(:daily_calories)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :daily_calories, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
<p class="notice"><%= notice %></p>
  <% end %>
<% if alert %>
<p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">DietApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
      <li class="nav-item active">
        <a class="nav-link" href="/meals">Meals listing<span class="sr-only">(current)</span></a>
      </li>
      <% end %>
    </ul>
  </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <% if current_user.role == 'manager' %>
        <li class="nav-item" id="log-out">
          <p><%= link_to 'Manager panel', manager_path %></p>
        </li>
          <% elsif current_user.role == 'admin' %>
          <li class="nav-item" id="log-out">
            <p><%= link_to 'Admin panel', admin_path %></p>
          </li>
        <% end %>
        <li class="nav-item" id="log-out">
        <p><%= link_to 'Log out', destroy_user_session_path, method: :delete %></p>
        </li>
      <% else %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item" id="sign-in">
        <p><%= link_to 'Sign in', user_session_path %></p>
      </li>
    </ul>
      <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <div class="container", style="margin-top: 20px">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/meals/_form.html.erb
<% if @meal.errors.any? %>
  <h4>Error was caused by following limits:</h4>
  <ul>
    <% @meal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @meal do |f| %>
  <p>
    <%= f.label :date %>
    <%= f.text_field :date %>
    <small class="form-text text-muted">Format: YYYY-MM-DD</small>
  </p>
  <p>
    <%= f.label :meal_type %>
    <%= f.select :meal_type, options_for_select(Meal.meal_types) %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :calories %>
    <%= f.text_field :calories %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to meals listing", meals_path %>

app/views/meals/edit.html.erb
<h1>Edit a meal</h1>

<%= render 'form' %>

app/views/meals/filter.html.erb
<h3>Your meals history</h3>
<br>
<h1>Meals:</h1>
<% if !current_user.user? %>
  <div class="row">
    <div class="col-9">
      <br>
      <%= will_paginate @filtered_meals, :page_links => false %>
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Meal</th>
          <th scope="col">Calories</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @filtered_meals.each do |meal| %>
          <tr>
            <td><%= meal.user.email %></td>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    </table>
  </div>
<% else %>
  <div class="row">
    <div class="col-9">
      <br>
      <%= will_paginate @filtered_meals, :page_links => false %>
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Meal</th>
          <th scope="col">Calories</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @filtered_meals.each do |meal| %>
          <tr>
            <td><%= meal.user.email %></td>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    </table>
  </div>
<% end %>
<p>Format: YYYY-MM-DD</p>
<%= form_for :filter do |f| %>
  <p>
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to today\'s meals', meals_path %>
<br>
<%= link_to 'Back to history', meals_history_path %>

app/views/meals/filter_new.html.erb
<h3>Your meals history</h3>
<br>
<h1>Meals:</h1>
<% if !current_user.user? %>
<div class="row">
  <div class="col-9">
    <br>
    <%= will_paginate @filtered_meals, :page_links => false %>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Date</th>
        <th scope="col">Type</th>
        <th scope="col">Meal</th>
        <th scope="col">Calories</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @filtered_meals.each do |meal| %>
        <tr>
          <td><%= meal.user.email %></td>
          <td><%= meal.date %></td>
          <td><%= meal.meal_type %></td>
          <td><%= meal.name %></td>
          <td><%= meal.calories %></td>
          <td><%= link_to 'Show', meal_path(meal) %></td>
          <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
          <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  </table>
</div>
  <% else %>
  <div class="row">
    <div class="col-9">
      <br>
      <%= will_paginate @filtered_meals, :page_links => false %>
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Meal</th>
          <th scope="col">Calories</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @filtered_meals.each do |meal| %>
          <tr>
            <td><%= meal.user.email %></td>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    </table>
  </div>
  <% end %>
<p>Format: YYYY-MM-DD</p>
<%= form_for :filter do |f| %>
  <p>
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back to today\'s meals', meals_path %>
<br>
<%= link_to 'Back to history', meals_history_path %>

app/views/meals/index.html.erb
<h3>Your today's ration is <%= current_user.daily_calories %> calories</h3>
<% if current_user.calories_left > 0 %>
<h3>You can take today no more than <%= current_user.calories_left  %> calories</h3>
<% else %>
<h3>You took today enough calories. Excess: <%= current_user.calories_taken - current_user.daily_calories %> calories. </h3>
<% end %>
<br>
<h1>Meals:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Type</th>
        <th scope="col">Meal</th>
        <th scope="col">Calories</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
      </thead>
      <% if current_user.calories_left > 0 %>
      <tbody>
      <%= will_paginate @user_meals, :page_links => false %>
      <% @user_meals.each do |meal| %>
        <tr>
          <td class="green"><%= meal.date %></td>
          <td class="green"><%= meal.meal_type %></td>
          <td class="green"><%= meal.name %></td>
          <td class="green"><%= meal.calories %></td>
          <td><%= link_to 'Show', meal_path(meal) %></td>
          <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
          <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <% else %>
        <%= will_paginate @user_meals, :page_links => false %>
        <% @user_meals.each do |meal| %>
          <tr>
            <td class="red"><%= meal.date %></td>
            <td class="red"><%= meal.meal_type %></td>
            <td class="red"><%= meal.name %></td>
            <td class="red"><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
    </table>
  </div>
    <br>

    <%= link_to 'Add a meal', new_meal_path %>
    <br>
    <%= link_to 'Change calories daily limit', edit_limit_path(current_user) %>
    <br>
    <%= link_to 'Go to meals history', meals_history_path %>

app/views/meals/meals_history.html.erb
<h3>Your meals history</h3>
<br>
<h1>Meals:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <% if current_user.user? %>
      <%= will_paginate @user_meals, :page_links => false %>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">Date</th>
        <th scope="col">Type</th>
        <th scope="col">Meal</th>
        <th scope="col">Calories</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
      </thead>
        <tbody>
          <% @user_meals.each do |meal| %>
            <tr>
              <td><%= meal.date %></td>
              <td><%= meal.meal_type %></td>
              <td><%= meal.name %></td>
              <td><%= meal.calories %></td>
              <td><%= link_to 'Show', meal_path(meal) %></td>
              <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
              <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
       </tbody>
    </table>
    <% else %>
      <%= will_paginate @meals_all, :page_links => false %>
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Meal</th>
          <th scope="col">Calories</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @meals_all.each do |meal| %>
          <tr>
            <td><%= meal.user.email %></td>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
  </table>
</div>
<%= link_to "Back to today's meals", meals_path %>
<br>
<%= link_to "Filter data", filter_path %>

app/views/meals/new.html.erb
<h1>Add a meal</h1>

<%= render 'form' %>

app/views/meals/show.html.erb
<h1>Showing the requested meal:</h1>
<p>
  Date: <%= @meal.date %>
</p>

<p>
  Type: <%= @meal.meal_type %>
</p>

<p>
  Product: <%= @meal.name %>
</p>

<p>
  Calories: <%= @meal.calories %>
</p>

<%= link_to "Edit this meal", edit_meal_path(@meal) %> |

<%= link_to "Back to meals listing", meals_path %>

app/views/pages/home.html.erb
<div class='center jumbotron' style="margin-left: 40px">
<h1>Welcome to our Diet-App</h1>
<% if current_user %>
    <h2><%= link_to 'Your meals', meals_path, class: "btn btn-danger btn-lg btn-xlarge" %></h2>
  <% else %>
    <h2><%= link_to 'Sign in', user_session_path, class: "btn btn-danger btn-lg btn-xlarge" %> |
      <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-danger btn-lg btn-xlarge" %></h2>
<% end %>
</div>

app/views/users/admin_new_user.html.erb
<%= form_for :user do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, autocomplete: 'current-password', class: 'form-control' %>

    <% if @minimum_password_length %>
      <small class="form-text text-muted"><%= t('devise.shared.minimum_password_length', count: @minimum_password_length) %></small>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, autocomplete: 'current-password', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :daily_calories %>
    <%= f.text_field :daily_calories, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Add new user', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/admin_panel.html.erb
<h1>Meals:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <%= will_paginate @meals_all, :page_links => false %>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Date</th>
        <th scope="col">Type</th>
        <th scope="col">Meal</th>
        <th scope="col">Calories</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @meals_all.each do |meal| %>
        <tr>
          <td><%= meal.user.email %></td>
          <td><%= meal.date %></td>
          <td><%= meal.meal_type %></td>
          <td><%= meal.name %></td>
          <td><%= meal.calories %></td>
          <td><%= link_to 'Show', meal_path(meal) %></td>
          <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
          <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<h1>Users:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">User</th>
        <th colspan="4" class="text-center">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% User.all.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= link_to 'Show user', user_path(user) %></td>
          <td><%= link_to 'Edit user', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy user', admin_destroy_user_path(user), method: :delete, data: { confirm: "You sure?" } %></td>
          <% if user.user? %>
          <td><%= link_to 'Give manager role', toggle_manager_path(user), method: :post, data: { confirm: "You sure?" } %></td>
          <% elsif user.manager? %>
          <td><%= link_to 'Demote manager', toggle_manager_path(user), method: :post, data: { confirm: "You sure?" } %></td>
          <% else %>
          <td>Immune user (Admin)</td>
           </tr>
          <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= link_to 'Add new user', admin_new_user_path %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :daily_calories %>
    <%= f.text_field :daily_calories %>
  </p>
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to admin panel", admin_path %>

app/views/users/limit_edit.html.erb
<%= form_for :user do |f| %>
  <p>
    <%= f.label :daily_calories %>
    <%= f.text_field :daily_calories %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/manager_panel.html.erb
<h1>Meals:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Date</th>
        <th scope="col">Type</th>
        <th scope="col">Meal</th>
        <th scope="col">Calories</th>
        <th colspan="3" class="text-center">Actions</th>
      </tr>
      </thead>
        <tbody>
        <%= will_paginate @meals_all, :page_links => false %>
        <% @meals_all.each do |meal| %>
          <tr>
            <td><%= meal.user.email %></td>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>
<h1>Users daily calories:</h1>
<div class="row">
  <div class="col-9">
    <br>
    <table class="table table-bordered table-hover">
      <thead>
      <tr>
        <th scope="col">User</th>
        <th colspan="2">Daily calories limit</th>
        <th colspan="1" class="text-center">Action</th>
      </tr>
      </thead>
      <tbody>
      <% User.all.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.daily_calories %></td>
          <td><%= link_to 'Edit', edit_limit_path(user) %></td>
          <td><%= link_to 'Show user', user_path(user) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<h1>Showing the requested user:</h1>
<p>
  User: <%= @user.email %>
</p>

<p>
  Daily calories: <%= @user.daily_calories %>
</p>

<p>
  Date registered: <%= @user.created_at.strftime("%F") %>
</p>

<p>
  Role: <%= @user.role %>
</p>

<div class="row">
  <div class="col-9">
    <br>
      <%= will_paginate @user_meals, :page_links => false %>
      <table class="table table-bordered table-hover">
        <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Type</th>
          <th scope="col">Meal</th>
          <th scope="col">Calories</th>
          <th colspan="3" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        <% @user_meals.each do |meal| %>
          <tr>
            <td><%= meal.date %></td>
            <td><%= meal.meal_type %></td>
            <td><%= meal.name %></td>
            <td><%= meal.calories %></td>
            <td><%= link_to 'Show', meal_path(meal) %></td>
            <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
            <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
</div>

<% if !current_user.user? %>
  <%= link_to 'Edit user', edit_user_path %>
<% end %>